### ISSUE TITLE
비밀번호 인코딩 문제

### ISSUE THREAD

**Issue by chupark** [krazuregame/development#1]
안녕하세요

비밀번호를 LoginCred.txt 파일로 저장할때 인코딩 문제가 있는것 같습니다.

현재 앱 비밀번호를 자동으로 생성하게 되있는데, Local PC 에서 생성한 비밀번호 파일을 
Azure상의 가상머신에 그대로 썼을때 로그인이 안되는 현상이 발생합니다.
SecureString으로 변환할 때도 에러가 발생합니다.

그러나 비밀번호를 스크립트 상에 직접 쓰는 경우 Local PC, AzureVM 모두 로그인이 가능합니다.

**Comment by cosmos0703** [comment]
안녕하세요 해당 내용 감사합니다.  
확인해보고 올려놓겠습니다. 감사합니다.
